### ISSUE TITLE
Compile Error on Ubuntu 18.04, driver c7

### ISSUE THREAD

**Issue by NanoExplorer** [multi-channel-electronics/mas#5]
Hello! I am in the process of updating my MAS installation (standard updates to Ubuntu 18.04 seem to have broken the version I've been using). However after cloning this repository and running configure, the compiler reported the following error:

```
make[2]: Entering directory '/home/mce/src/mas/interfaces/mce_library'
cc -Wall -g -O2 -fPIC -fno-stack-protector -I ../../include -DMAS_PREFIX="\"/usr/mce\"" -DMAS_ETCDIR="\"/etc/mce\"" -DMAS_CONFDIR="\"\"" -DMAS_JAMDIR="\"/usr/mce/firmware\"" -DMAS_ROOTDIR="\"/usr/mce/mce_script\"" -DMAS_TEMPDIR="\"/tmp\"" -DMAS_DATAROOT="\"/data/cryo\"" -DMAS_DATADIR="\"current_data\""  -c -o acq.o acq.c
cc -Wall -g -O2 -fPIC -fno-stack-protector -I ../../include -DMAS_PREFIX="\"/usr/mce\"" -DMAS_ETCDIR="\"/etc/mce\"" -DMAS_CONFDIR="\"\"" -DMAS_JAMDIR="\"/usr/mce/firmware\"" -DMAS_ROOTDIR="\"/usr/mce/mce_script\"" -DMAS_TEMPDIR="\"/tmp\"" -DMAS_DATAROOT="\"/data/cryo\"" -DMAS_DATADIR="\"current_data\""  -c -o cmd.o cmd.c
cmd.c: In function ‘mcecmd_send_command_simple’:
cmd.c:296:5: error: expected ‘,’ or ‘;’ before ‘cmd’
     cmd.data[0] = 1;
     ^~~
<builtin>: recipe for target 'cmd.o' failed
```

I wonder if there's a semicolon missing on the line I reference below?

 https://github.com/multi-channel-electronics/mas/blob/942237fd15c0b320a6275201d0f4819c5099586d/interfaces/mce_library/cmd.c#L294

I'm going to try editing it locally and see if it works, and I'll report back.

Thanks!

**Comment by NanoExplorer** [comment]
Looks like there are a couple more:
https://github.com/multi-channel-electronics/mas/blob/942237fd15c0b320a6275201d0f4819c5099586d/interfaces/mce_library/dirfile.c#L532

https://github.com/multi-channel-electronics/mas/blob/942237fd15c0b320a6275201d0f4819c5099586d/interfaces/mce_library/dirfile.c#L657

After adding these 3 semicolons, though, the software does compile successfully. Our MCE is not online at the moment however, so I can't really do much testing other than confirming that the fiber card device is behaving itself.

**Comment by nasamaher** [comment]
My first compile today and I too had to add the three semicolons.  I'm a bit surprised the fix is not in the master branch as it's been a while.
